import type { Mission } from "./types";

export const MISSIONS: Mission[] = [
  {
    id: "checkout",
    number: 1,
    product: "MarketOS",
    title: "Checkout under pressure",
    objective:
      "Release candidate 2.4 is taking live payments. Find the three defects before the deployment window closes.",
    route: "staging.marketos.test/checkout",
    timeLimit: 72,
    bugs: [
      {
        id: "CHK-101",
        title: "Applied coupon does not reduce the order",
        shortLabel: "Discount ignored",
        severity: "P1",
        actual: "The SAVE20 coupon is marked as applied, but discount remains $0.00.",
        expected: "The order total should include the 20% coupon reduction.",
        evidence: "Coupon row and totals disagree in the order summary.",
        hotspot: { left: 5, top: 44, width: 39, height: 15 },
      },
      {
        id: "CHK-102",
        title: "Order total is mathematically incorrect",
        shortLabel: "Wrong total",
        severity: "P0",
        actual: "Subtotal $88.00 plus shipping $5.00 is displayed as $138.99.",
        expected: "The total should equal $93.00 before any valid discount.",
        evidence: "Visible line items do not add up to the displayed total.",
        hotspot: { left: 5, top: 63, width: 39, height: 17 },
      },
      {
        id: "CHK-103",
        title: "Full card number remains visible",
        shortLabel: "Card data exposed",
        severity: "P0",
        actual: "The payment form displays the complete card number after entry.",
        expected: "All but the last four card digits should be masked.",
        evidence: "Sensitive payment data is readable in the card field.",
        hotspot: { left: 52, top: 37, width: 42, height: 15 },
      },
    ],
  },
  {
    id: "auth",
    number: 2,
    product: "Northstar ID",
    title: "Authentication breach",
    objective:
      "A new sign-in screen is ready for production. Identify the security and UX regressions hidden in the flow.",
    route: "id.northstar.test/sign-in",
    timeLimit: 68,
    bugs: [
      {
        id: "AUTH-201",
        title: "Password is rendered as plain text",
        shortLabel: "Password exposed",
        severity: "P0",
        actual: "The password value `supersecret123` is visible on screen.",
        expected: "Password characters should be masked by default.",
        evidence: "Credential text is readable without revealing the field.",
        hotspot: { left: 45, top: 38, width: 44, height: 14 },
      },
      {
        id: "AUTH-202",
        title: "Server stack trace is exposed to users",
        shortLabel: "Stack trace leaked",
        severity: "P1",
        actual: "A failed request renders an internal Node.js stack trace.",
        expected: "The UI should show a safe, actionable authentication error.",
        evidence: "Internal file paths and service names appear in the alert.",
        hotspot: { left: 43, top: 54, width: 48, height: 15 },
      },
      {
        id: "AUTH-203",
        title: "Primary sign-in action has the wrong label",
        shortLabel: "Wrong CTA",
        severity: "P2",
        actual: "The primary action says `Create account` on the sign-in form.",
        expected: "The primary action should clearly say `Sign in`.",
        evidence: "The page title and primary action describe different flows.",
        hotspot: { left: 49, top: 75, width: 37, height: 12 },
      },
    ],
  },
  {
    id: "support",
    number: 3,
    product: "Relay Desk",
    title: "Privacy incident",
    objective:
      "Customer support is processing a sensitive refund. Stop the privacy and routing defects before the reply is sent.",
    route: "relaydesk.test/tickets/4821",
    timeLimit: 70,
    bugs: [
      {
        id: "SUP-301",
        title: "Customer national ID is not masked",
        shortLabel: "PII exposed",
        severity: "P0",
        actual: "The customer profile shows the complete national ID.",
        expected: "Sensitive identifiers should be masked and access controlled.",
        evidence: "Full PII is visible in the ticket sidebar.",
        hotspot: { left: 4, top: 47, width: 27, height: 15 },
      },
      {
        id: "SUP-302",
        title: "Overdue SLA is shown as healthy",
        shortLabel: "SLA status wrong",
        severity: "P1",
        actual: "A ticket overdue by 2h 14m has a green `On track` status.",
        expected: "The ticket should be marked overdue and escalated.",
        evidence: "The SLA duration conflicts with the green status badge.",
        hotspot: { left: 72, top: 13, width: 23, height: 17 },
      },
      {
        id: "SUP-303",
        title: "Reply is addressed to the wrong customer",
        shortLabel: "Wrong recipient",
        severity: "P0",
        actual: "The reply composer targets `maria@example.com` for Alex's ticket.",
        expected: "The reply recipient should match the ticket customer.",
        evidence: "Customer profile and composer recipient are inconsistent.",
        hotspot: { left: 35, top: 65, width: 59, height: 14 },
      },
    ],
  },
];

export const TOTAL_BUGS = MISSIONS.reduce(
  (total, mission) => total + mission.bugs.length,
  0,
);
